---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  - name: Install apache package
    apt:
      name: python-pexpect
      update-cache: no
      state: present
  - name: gather facts
    setup:
  tags:
    - always

- hosts: all
  gather_facts: True