---

- template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - common

- name: Install heimdal-clients package
  apt:
    name: heimdal-clients
    update-cache: no
    state: present
  tags:
    - common

- name: Install expect package
  apt:
    name: expect
    update-cache: no
    state: present
  tags:
    - common
